# Site settings
title: Capital Chaplains
email: steve@capchaps.org
description: Providing help and hope to company owners, managers, and employees by building relationships and serving through a Chaplain Assistance Program.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.capchaps.org" # the base hostname & protocol for your site
permalink: /:categories/:title/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
markdown: kramdown
