# Site settings
title: Capital Chaplains
email: steve@capchaps.org
description: Providing help and hope to company owners, managers, and employees by building relationships and serving through a Chaplain Assistance Program.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.capchaps.org" # the base hostname & protocol for your site
permalink: /:categories/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
collections:
  - chaplains
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-srcset
markdown: kramdown
srcset:
  cache: "/tmp/images"
